version: '2'
services:
  apache:
    build:
      context: ../../../
      dockerfile: ./shared/dockerfiles/Microservice.Dockerfile
    expose:
      - 80
      - 443
    command: ["apache2ctl", "-D", "FOREGROUND"]
    volumes:
      - apache-logs:/var/log/container

