version: '2'
services:
  apache:
    build:
      context: ../../../
      dockerfile: ./shared/dockerfiles/Service.Dockerfile
    expose:
      - 80
      - 443
    command: ["apache2ctl", "-D", "FOREGROUND"]
    volumes:
      #      - $SSH_AUTH_SOCK:/ssh-agent
      - apache-logs:/var/log/container
#    environment:
#      - SSH_AUTH_SOCK=/ssh-agent
