---

- name: Add Software Properties Common
  apt:
    name:
      - software-properties-common

- name: Add PHP repo
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP {{ PHP_VERSION }}
  apt:
    name:
      - php{{ PHP_VERSION }}
      - php{{ PHP_VERSION }}-curl
      - php{{ PHP_VERSION }}-dev
      - php{{ PHP_VERSION }}-gd
      - php{{ PHP_VERSION }}-mbstring
      - php{{ PHP_VERSION }}-mysql
      - php{{ PHP_VERSION }}-xml
      - php{{ PHP_VERSION }}-xmlrpc
      - php{{ PHP_VERSION }}-zip
      - php{{ PHP_VERSION }}-bcmath
      - php{{ PHP_VERSION }}-xdebug
      - libapache2-mod-php{{ PHP_VERSION }}
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Set PHP upload max filesize
  lineinfile: 
    dest: /etc/php/{{ PHP_VERSION }}/apache2/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 800M"
    state: present

- name: Set PHP post max filesize    
  lineinfile: 
    dest: /etc/php/{{ PHP_VERSION }}/apache2/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 800M"
    state: present